version: "3.7"

services:

  user--service-db:
    image: postgres
    container_name: user--service-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: user
    volumes:
      - pgusuariodata:/data/postgres

volumes:
  pgusuariodata: